const quotes=["Believe you can and you're halfway there.",
    "Success is not final, failure is not fatal.",
    "Dream big and dare to fail.",
    "The future depends on what you do today.",
    "Never stop learning.",
    "Do what you can, with what you have, where you are.",
    "Stay hungry, stay foolish.",
    "Knowledge is power.",
    "Action is the foundational key to all success.",
    "Opportunities don't happen, you create them.",
    "The best way to predict the future is to create it.",
    "Small steps every day lead to big results.",
    "Work hard in silence, let success make the noise.",
    "Great things never come from comfort zones.",
    "Don't watch the clock; do what it does. Keep going.",
    "Everything you can imagine is real.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The secret of getting ahead is getting started.",
    "Difficulties strengthen the mind.",
    "Your limitation—it's only your imagination.",
    "Push yourself because no one else is going to do it for you.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Start where you are. Use what you have. Do what you can.",
    "Success is the sum of small efforts repeated daily.",
    "You miss 100% of the shots you don't take.",
    "Discipline is the bridge between goals and accomplishment.",
    "If you can dream it, you can do it.",
    "The journey of a thousand miles begins with one step.",
    "Hard work beats talent when talent doesn't work hard.",
    "The only way to do great work is to love what you do.",
    "Every accomplishment starts with the decision to try.",
    "Failure is another stepping stone to greatness.",
    "The expert in anything was once a beginner.",
    "Focus on progress, not perfection.",
    "Be stronger than your excuses.",
    "Your future is created by what you do today.",
    "Success is a journey, not a destination.",
    "The best revenge is massive success.",
    "Never give up on a dream because of the time it will take.",
    "If opportunity doesn't knock, build a door.",
    "Don't limit your challenges. Challenge your limits.",
    "A year from now you may wish you had started today.",
    "Strive for progress, not perfection.",
    "Doubt kills more dreams than failure ever will.",
    "Work until your idols become your rivals.",
    "Success is getting what you want.",
    "Persistence guarantees that results are inevitable.",
    "Every day is a chance to get better.",
    "Motivation gets you started. Habit keeps you going.",
    "Nothing worth having comes easy.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Turn your wounds into wisdom.",
    "Don't be afraid to give up the good for the great.",
    "You are capable of amazing things.",
    "The only limit is the one you set yourself.",
    "Make each day your masterpiece.",
    "Success begins at the end of your comfort zone.",
    "Never regret anything that made you smile.",
    "You don't have to be great to start, but you have to start to be great.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Every moment is a fresh beginning.",
    "What we think, we become.",
    "Success is liking yourself and what you do.",
    "Be so good they can't ignore you.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "A goal without a plan is just a wish.",
    "Nothing is impossible; the word itself says I'm possible.",
    "Keep your face always toward the sunshine.",
    "Don't count the days, make the days count.",
    "The harder the battle, the sweeter the victory.",
    "Believe in yourself and all that you are.",
    "You are stronger than you think.",
    "Every strike brings me closer to the next home run.",
    "Don't let yesterday take up too much of today.",
    "The best preparation for tomorrow is doing your best today.",
    "Success is where preparation and opportunity meet.",
    "Aim for the moon. If you miss, you may hit a star.",
    "Learn as if you will live forever.",
    "Live as if you will die tomorrow.",
    "The only impossible journey is the one you never begin.",
    "Do something today that your future self will thank you for.",
    "Quality means doing it right when no one is looking.",
    "Nothing will work unless you do.",
    "Be yourself; everyone else is already taken.",
    "It always seems impossible until it's done.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Success is not in what you have, but who you are.",
    "Don't quit. Suffer now and live the rest of your life as a champion."]

function show(){
    const random=Math.floor(Math.random()*quotes.length);
    document.getElementById("quote").textContent = quotes[random];
}